name: Terragrunt - AWS Org

on:
  push:
    branches: [ main ]
    paths: 
      - 'organization/kloud/global/**'
  pull_request:
    types: 
      - assigned
      - opened
      - synchronize
      - reopened
    paths: 
      - 'organization/kloud/global/**'

jobs:
  terragrunt:
    uses: kolvin/workflows/.github/workflows/terragrunt.yaml@v1.8.0
    with:
      working-directory: "organization/kloud/global"
      target-account-id: "016272825626"
      target-region: "eu-west-1"
