name: vpc-prod-eu-west-1 

on:
  pull_request:
    branches: main
    types: 
      - assigned
      - opened
      - synchronize
      - reopened
    paths: 
      - 'vpc/prod/eu-west-1/**'
      - '.github/workflows/terragrunt-prod-vpc.yml'
      - 'common.hcl'
  push:
    branches: main

jobs:
  terragrunt:
    uses: kloud-cnf/workflows/.github/workflows/terragrunt.yaml@v0.3.7
    with:
      working-directory: "vpc/prod/eu-west-1"
      target-account-id: "310394544294"
      target-region: "eu-west-1"
      ci-role-name: "github-ci-infrastructure-provisoner"
