name: vpc-dev-main-eu-west-1 

on:
  pull_request:
    branches: main
    types: 
      - assigned
      - opened
      - synchronize
      - reopened
    paths: 
      - 'vpc/dev/eu-west-1/main/**'
      - '.github/workflows/terragrunt-dev-main-vpc.yml'
      - 'common.hcl'
  push:
    branches: main
    paths:
      - 'vpc/dev/eu-west-1/**'
      - '.github/workflows/terragrunt-dev-main-vpc.yml'
      - 'common.hcl'

jobs:
  terragrunt:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: kloud-cnf/workflows/.github/workflows/terragrunt.yaml@v0.3.7
    with:
      working-directory: "vpc/dev/eu-west-1/main"
      target-account-id: "943824751361"
      target-region: "eu-west-1"
      ci-role-name: "github-ci-infrastructure-provisoner"
